### ISSUE TITLE
init() function seems to have error

### ISSUE THREAD

**Issue by eroteme** [morvencao/kube-mutating-webhook-tutorial#1]
When I try to compile kube-mutating-webhook-tutorial/webhook.go I get an error that 	
`_ = v1.AddToScheme(runtimeScheme)` 

does not exist

> ./webhook.go:70:20: cannot use runtimeScheme (type *"k8s.io/apimachinery/pkg/runtime".Scheme) as type *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Scheme in argument to "k8s.io/kubernetes/pkg/apis/core/v1".AddToScheme

When I comment out this line it seems to compile.

**Comment by sedooe** [comment]
You should `dep ensure` first.

**Comment by chanehua** [comment]
> You should `dep ensure` first.
I have the same issue; I had executed "go get -u github.com/golang/dep/cmd/dep";but also report : 
./webhook.go:91:20: cannot use runtimeScheme (type *"k8s.io/apimachinery/pkg/runtime".Scheme) as type *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Scheme in argument to "k8s.io/kubernetes/pkg/apis/core/v1".AddToScheme.
I cloud not find process issue method now.

**Comment by chanehua** [comment]
I execute "dep ensure" command after，go install well. thx！
