### ISSUE TITLE
关于API Server调用webhook报文格式的咨询

### ISSUE THREAD

**Issue by darren-wang** [morvencao/kube-mutating-webhook-tutorial#33]
您好，想请教一下API Server调用webhook扩展时报文是JSON的还是protobuf的，因为我们的技术栈是以Java为主，对Go不是很了解，所以想尝试看看Java能不能实现类似的功能，目前就是对报文的形式不是很了解，我看Go的参数声明中既有JSON的又有protouf的，想跟您咨询一下API Server调用webhook扩展时报文的形式，是JSON还是protobuf，还是可以配置的，非常感谢！

**Comment by morvencao** [comment]
it should be JSON format, because the http request hander has `Content-Type=application/json`, but I'm sure if it can be configured to the protobuf format.

**Comment by darren-wang** [comment]
> it should be JSON format, because the http request hander has `Content-Type=application/json`, but I'm sure if it can be configured to the protobuf format.

Thanks a lot, I will try it.
