### ISSUE TITLE
I have the followed issues, when install modules    

### ISSUE THREAD

**Issue by spursy** [morvencao/kube-mutating-webhook-tutorial#9]
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "k8s.io/apimachinery": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://k8s.io/apimachinery?go-get=1": Get http://k8s.io/apimachinery?go-get=1: EOF
  ✗ unable to deduce repository and source type for "k8s.io/api": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://k8s.io/api?go-get=1": Get http://k8s.io/api?go-get=1: EOF

**Comment by morvencao** [comment]
Have migrated dependency management tool from dep to go mod in https://github.com/morvencao/kube-mutating-webhook-tutorial/pull/11, please try again.
Feel free to reopen if you still have issue.
